### ISSUE TITLE
Remove a credit card

### ISSUE THREAD

**Issue by couraudt** [monetizejs/monetize.js#1]
Hi benweet,

Thanks for this real good web app.
I wondering how to delete a credit card in your application?

Thanks

**Comment by benweet** [comment]
Hi,
It's not possible at the moment. You can only update a card in "My account".
If you have paid for a subscription option, you can unsubscribe in "My apps". It will end the subscription at the end of the billing period.
I hope it helps.

**Comment by couraudt** [comment]
Thanks a lot.

**Comment by scarlettfres** [comment]
Hey! Is it still not possible to delete the credit card? I am not so found of leaving those informations in too many websites...

**Comment by Beej126** [comment]
if you find it as heavy handed as i do to take this kind of critical info without a way of clearing it out, here is one way, albeit with some effort... Bank of America provides a "virtual" credit card facility called "Shop Safe"... we can cut a new card number at will, even with $0.01 and then throw that into MonetizeJS.

**Comment by swift-fox** [comment]
Hi benweet,

As a user, I feel really uncomfortable to left my credit card info in your system knowing it's no longer needed. So please allow users to delete such info. If it's a technical difficulty, please try to resolve by any means, because it might be illegal to retain personal information for extended time and purpose.

Thanks

**Comment by jofftiquez** [comment]
It's 2018 and I still can't remove my card. My previous card was already expired and I don't want to update my card info, it's so annoying to get emails from monetize about my failed payment. Please do something about this. Thank you.
